services:
  mysql:
    image: mysql:8.1
    container_name: user-db
    ports:
      - "2706:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: user_service
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 15s
      timeout: 15s
      retries: 3
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - network
  user:
    container_name: user-service
    hostname: user-service-1
    ports:
      - "80:8080"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PROFILE_ACTIVE: prod
      DB_HOST: mysql:3306
      DB_USER: admin
      DB_PASSWORD: admin
      DB_DATABASE: user_service
      KC_SERVER_URL: http://keycloak-server:443
      KC_REALM: realm
      KC_CLIENT_ID: client-id
      KC_CLIENT_SECRET: secret
#      KC_TOKEN_PATH: /protocol/openid-connect/token
      SWAGGER_SERVER_URL: http://gateway:80
    volumes:
      - logs:/app/logs
    depends_on:
      mysql:
        condition: service_healthy
        restart: true
    networks:
      - network
volumes:
  logs:
    name: user-logs
  db-data:
    name: user-db
networks:
  network:
    name: user-network