services:
  mysql:
    image: mysql:8.1
    container_name: user-db
    ports:
      - "2706:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 15s
      timeout: 15s
      retries: 3
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - network
  user:
    container_name: user-service
    hostname: user-service-1
    ports:
      - "80:8080"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: mysql:3306
      PROFILE_ACTIVE: test

      KC_SERVER_URL: https://keycloak-server:443
      KC_REALM: realm
      KC_CLIENT_ID: client-id
      KC_CLIENT_SECRET: secret
#      KC_TOKEN_PATH: /protocol/openid-connect/token

      EUREKA_APP_NAME: user-service
      EUREKA_IP_ADDR: 127.0.0.1
      EUREKA_PORT: 80
      REGISTER_ZONE: service-registry-1
      DEFAULT_ZONE: http://admin:admin@service-registry:80/eureka/

      SWAGGER_SERVER_URL: http://gateway:80
    env_file:
      - .env
    volumes:
      - logs:/app/logs
    depends_on:
      mysql:
        condition: service_healthy
        restart: true
    networks:
      - network
volumes:
  logs:
    name: user-logs
  db-data:
    name: user-db
networks:
  network:
    name: user-network