spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_service
    username: admin
    password: admin
  cloud:
    discovery:
      enabled: false
eureka:
  client:
    enabled: false
keycloak:
  server-url: http://34.80.75.198
  realm: sc-microservices
  client-id: sc-mobile-app
  client-secret: lzvqlZZbrpjSY5ZkHHdnPQGd6arhpdaW