spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_service
    username: admin
    password: admin
  cloud:
    discovery:
      enabled: false
eureka:
  client:
    enabled: false
keycloak:
  server-url: localhost
  realm: realm-name
  client-id: client-id
  client-secret: client-secret